name: MATLAB Tests
on: [push]

jobs:

  test:
    name: Run MATLAB Tests and Package Artifacts
    strategy:
      matrix:
        release: ["R2023b", "R2024a"]
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2.1.2
        with:
          release: ${{ matrix.release }}
          products: Statistics_and_Machine_Learning_Toolbox
      - name: Run build tool
        uses: matlab-actions/run-build@v2.2.1
      - name: Package artifacts
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: MATLAB Test Results
          path: 'results.xml'
          working-directory: 'tests/artifacts'
          reporter: java-junit
      - name: Report coverage
        uses: 5monkeys/cobertura-action@master
        with:
          path: 'tests/artifacts/coverage.xml'
          minimum_coverage: 75
          report_name: Coverage Report
