name: MATLAB Tests
on: [push]

jobs:

  test:
    name: Run MATLAB Tests and Package Artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v1
        with: 
          release: R2023b
      - name: Run build tool
        uses: matlab-actions/run-build@v1
      - name: Package artifacts
        uses: dorny/test-reporter@v1
        if: success() || failure()    
        with:
          name: MATLAB Test Results
          path: '*.xml'    
          working-directory: 'tests/artifacts'
          reporter: java-junit
